"""
app/integrations/webhooks/seeder.py
Seeds crm_integrations from .env at startup.
"""

from __future__ import annotations

import logging
import uuid
from sqlalchemy import select

from app.core.database import async_session_maker
from app.core.settings import get_settings
from app.models.crm_integration import CrmIntegration
from app.models.source_system import SourceSystem

logger = logging.getLogger(__name__)

async def seed_crm_integrations() -> None:
    """
    Seeds CrmIntegration records from environment configuration.
    
    Note: webhook_uuid is AUTO-GENERATED by the database (uuid4).
    Do NOT set it manually — the model's default=uuid.uuid4 handles this.
    
    For testing:
    1. Create integration: INSERT INTO crm_integrations (tenant_id, source_system_id, auth_type, ...)
    2. Database auto-generates webhook_uuid
    3. Query to get it: SELECT webhook_uuid FROM crm_integrations WHERE source_system_id = 1
    4. Use URL: http://app:8000/webhooks/ingest/{webhook_uuid}
    """
    settings = get_settings()

    # 1. Mandatory Tenant Check
    # crm_integrations.tenant_id is NOT NULL. If missing, we must abort.
    raw_tenant_id = getattr(settings, "WEBHOOK_TENANT_ID", "")
    tenant_id: uuid.UUID | None = None
    
    if raw_tenant_id:
        try:
            tenant_id = uuid.UUID(raw_tenant_id)
        except ValueError:
            logger.error("WEBHOOK_TENANT_ID is invalid. Aborting CRM seeding.")
            return
    
    if not tenant_id:
        logger.warning(
            "WEBHOOK_TENANT_ID not set. CRM integrations require manual creation. "
            "See WEBHOOK_SETUP.md for details."
        )
        return

    # 2. Integration Config
    integrations_to_seed = [
        {
            "system_name": "espocrm",
            "base_url": getattr(settings, "ESPO_BASE_URL", "") or None,
            "auth_type": "api_key",
        },
        {
            "system_name": "zammad",
            "base_url": getattr(settings, "ZAMMAD_BASE_URL", "") or None,
            "auth_type": "bearer_token",
        },
    ]

    async with async_session_maker() as session:
        async with session.begin():
            for cfg in integrations_to_seed:
                # Lookup Source System
                ss_result = await session.execute(
                    select(SourceSystem).where(SourceSystem.system_name == cfg["system_name"])
                )
                source_system = ss_result.scalars().first()
                if not source_system:
                    logger.warning(
                        "Source system '%s' not found. Seed source_systems first.",
                        cfg["system_name"],
                    )
                    continue

                # Check if integration already exists for this tenant + source system
                existing = await session.execute(
                    select(CrmIntegration).where(
                        (CrmIntegration.tenant_id == tenant_id) &
                        (CrmIntegration.source_system_id == source_system.id)
                    )
                )
                if existing.scalars().first():
                    logger.debug(
                        "%s integration already exists for tenant %s — skipping",
                        cfg["system_name"],
                        tenant_id,
                    )
                    continue

                # Insert without setting webhook_uuid — let database auto-generate it
                integration = CrmIntegration(
                    tenant_id=tenant_id,
                    source_system_id=source_system.id,
                    # webhook_uuid: auto-generated by model's default=uuid.uuid4
                    base_url=cfg["base_url"],
                    auth_type=cfg["auth_type"],
                    key_version="v1",
                    is_active=True,
                    # Sensitive _enc columns default to None.
                    # Populated later via API/EncryptionService.
                )
                session.add(integration)
                logger.info(
                    "Seeded %s integration for tenant %s (webhook_uuid will be auto-generated)",
                    cfg["system_name"],
                    tenant_id,
                )

            await session.commit()
        
        logger.info("CRM integrations seeding complete")