"""add_deleted_at_to_dashboard_users

Revision ID: <will be auto-generated>
Revises: <your current head revision>
Create Date: <auto-generated>

Adds deleted_at to dashboard_users to track when an account was
deactivated.  Complements is_active=False so audit queries can
filter by deactivation date without a separate audit table.

NULL  → account is live
value → account was deactivated at this timestamp
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op


# ---------------------------------------------------------------------------
# Revision identifiers — leave the auto-generated values in place
# ---------------------------------------------------------------------------

revision: str = "<auto-generated>"
down_revision: str | None = "<your current head>"
branch_labels = None
depends_on = None


# ---------------------------------------------------------------------------
# Upgrade
# ---------------------------------------------------------------------------

def upgrade() -> None:
    op.add_column(
        "dashboard_users",
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment=(
                "Populated when is_active is set to False. "
                "NULL means the account is still live."
            ),
        ),
    )

    # Back-fill: any row that is already inactive gets deleted_at = updated_at
    # so the column is meaningful for existing soft-deleted accounts.
    op.execute(
        """
        UPDATE dashboard_users
        SET    deleted_at = updated_at
        WHERE  is_active  = FALSE
        """
    )


# ---------------------------------------------------------------------------
# Downgrade
# ---------------------------------------------------------------------------

def downgrade() -> None:
    op.drop_column("dashboard_users", "deleted_at")