"""add_crm_integrations

Revision ID: c17ef1f2f165
Revises: f06d2e27402c
Create Date: 2026-04-17 06:21:46.219453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c17ef1f2f165'
down_revision: Union[str, None] = 'f06d2e27402c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crm_integrations')
    op.alter_column('tenants', 'contact_email',
               existing_type=sa.VARCHAR(length=255),
               comment='Primary contact email for the tenant',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'contact_email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Primary contact email for the tenant',
               existing_nullable=True)
    op.create_table('crm_integrations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True, comment='Tenant owner — FK to tenants.id added via migration once that table exists'),
    sa.Column('source_system_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('webhook_uuid', sa.UUID(), autoincrement=False, nullable=False, comment='Paste into CRM webhook URL: /webhooks/ingest/{webhook_uuid}'),
    sa.Column('webhook_secret', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('webhook_secrets', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('api_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('base_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], name='crm_integrations_source_system_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='crm_integrations_pkey'),
    sa.UniqueConstraint('webhook_uuid', name='crm_integrations_webhook_uuid_key')
    )
    # ### end Alembic commands ###
