"""add_ticket_pending_until

Revision ID: f06d2e27402c
Revises: 
Create Date: 2026-04-13 07:57:20.435482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f06d2e27402c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crm_integrations')
    op.add_column('tickets', sa.Column('pending_until', sa.DateTime(timezone=True), nullable=True, comment='Deadline for the pending state. Required by some CRMs (e.g. Zammad pending_time). NULL when the ticket is not in a pending state.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'pending_until')
    op.create_table('crm_integrations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True, comment='Tenant owner — FK to tenants.id added via migration once that table exists'),
    sa.Column('source_system_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('webhook_uuid', sa.UUID(), autoincrement=False, nullable=False, comment='Paste into CRM webhook URL: /webhooks/ingest/{webhook_uuid}'),
    sa.Column('webhook_secret', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('webhook_secrets', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('api_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('base_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], name='crm_integrations_source_system_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='crm_integrations_pkey'),
    sa.UniqueConstraint('webhook_uuid', name='crm_integrations_webhook_uuid_key')
    )
    # ### end Alembic commands ###
