"""add_ticket_pending_until

Revision ID: fcf4d515747b
Revises: c17ef1f2f165
Create Date: 2026-04-21 06:27:16.458735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcf4d515747b'
down_revision: Union[str, None] = 'c17ef1f2f165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crm_integrations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_integrations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False, comment='FK -> tenants.id (ON DELETE CASCADE). Enforce via Alembic.'),
    sa.Column('source_system_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('webhook_uuid', sa.UUID(), autoincrement=False, nullable=False, comment='Opaque UUID in ingest URL: /webhooks/ingest/{webhook_uuid}'),
    sa.Column('credential_enc', sa.TEXT(), autoincrement=False, nullable=True, comment='Single AES-256-CBC encrypted JSON blob holding ALL secrets. Decrypted shape depends on auth_type (see module docstring).'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False, comment="Non-sensitive integration config. Queryable without decryption. Python attr='config', DB col='metadata'."),
    sa.Column('token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='NULL = no expiry. Set for OAuth2 / expiring tokens.'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Soft-disable without deleting.'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], name='crm_integrations_source_system_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='crm_integrations_pkey'),
    sa.UniqueConstraint('webhook_uuid', name='crm_integrations_webhook_uuid_key')
    )
    # ### end Alembic commands ###
