# """
# Table  invitations
# Tracks invitation links sent to admins and agents.
# Token is generated by the backend and embedded in the invite link.
# Status lifecycle: pending → accepted | expired | revoked
# """

# from __future__ import annotations

# import uuid
# from datetime import datetime

# from sqlalchemy import Boolean, DateTime, ForeignKey, String, func
# from sqlalchemy.dialects.postgresql import UUID
# from sqlalchemy.orm import Mapped, mapped_column, relationship

# from app.core.base import Base


# class Invitation(Base):
#     __tablename__ = "invitations"

#     # ------------------------------------------------------------------
#     # Primary key
#     # ------------------------------------------------------------------
#     id: Mapped[uuid.UUID] = mapped_column(
#         UUID(as_uuid=True),
#         primary_key=True,
#         default=uuid.uuid4,
#         comment="Invite identifier",
#     )

#     # ------------------------------------------------------------------
#     # Foreign key
#     # ------------------------------------------------------------------
#     tenant_id: Mapped[uuid.UUID] = mapped_column(
#         UUID(as_uuid=True),
#         ForeignKey("tenants.id", ondelete="CASCADE"),
#         nullable=False,
#         comment="Tenant the user will join",
#     )

#     # ------------------------------------------------------------------
#     # Invite details
#     # ------------------------------------------------------------------
#     email: Mapped[str] = mapped_column(
#         String(255),
#         nullable=False,
#         comment="Target recipient email",
#     )
#     token: Mapped[str] = mapped_column(
#         String(200),
#         nullable=False,
#         unique=True,
#         comment="Secure onboarding token embedded in the invite link",
#     )
#     role: Mapped[str] = mapped_column(
#         String(50),
#         nullable=False,
#         comment="Role to assign on acceptance: 'admin' or 'agent'",
#     )

#     # ------------------------------------------------------------------
#     # Status tracking
#     # ------------------------------------------------------------------
#     is_used: Mapped[bool] = mapped_column(
#         Boolean,
#         nullable=False,
#         default=False,
#         comment="Whether the invite link has been used",
#     )
#     status: Mapped[str] = mapped_column(
#         String(50),
#         nullable=False,
#         default="pending",
#         comment="pending | accepted | expired | revoked",
#     )
#     expires_at: Mapped[datetime] = mapped_column(
#         DateTime(timezone=True),
#         nullable=False,
#         comment="Validity period — link rejected after this timestamp",
#     )
#     accepted_at: Mapped[datetime | None] = mapped_column(
#         DateTime(timezone=True),
#         nullable=True,
#         default=None,
#         comment="When the invite was accepted",
#     )

#     # ------------------------------------------------------------------
#     # Audit
#     # ------------------------------------------------------------------
#     invited_by: Mapped[uuid.UUID | None] = mapped_column(
#         UUID(as_uuid=True),
#         ForeignKey("dashboard_users.id", ondelete="SET NULL"),
#         nullable=True,
#         comment="FK → dashboard_users — who sent this invite",
#     )
#     created_at: Mapped[datetime] = mapped_column(
#         DateTime(timezone=True),
#         nullable=False,
#         server_default=func.now(),
#         comment="When the invite was created",
#     )

#     # ------------------------------------------------------------------
#     # Relationships
#     # ------------------------------------------------------------------
#     tenant: Mapped["Tenant"] = relationship(  # type: ignore[name-defined]
#         "Tenant", lazy="noload"
#     )
#     inviter: Mapped["DashboardUser | None"] = relationship(  # type: ignore[name-defined]
#         "DashboardUser",
#         foreign_keys=[invited_by],
#         lazy="noload",
#     )

#     def __repr__(self) -> str:
#         return (
#             f"<Invitation id={self.id} email={self.email!r} "
#             f"status={self.status!r} tenant={self.tenant_id}>"
#         )

"""
Table  invitations
Invitation links sent to admins and agents.
Removed: is_used, accepted_at, invited_by, role fields.
Added: CHECK constraint on status.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import CheckConstraint, DateTime, ForeignKey, String, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.base import Base


class Invitation(Base):
    __tablename__ = "invitations"
    __table_args__ = (
        CheckConstraint(
            "status IN ('accepted', 'pending', 'rejected')",
            name="chk_invitations_status",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4,
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
    )
    email: Mapped[str] = mapped_column(String(255), nullable=False)
    token: Mapped[str] = mapped_column(
        String(200), nullable=False, unique=True,
        comment="Secure onboarding token embedded in the invite link",
    )
    status: Mapped[str] = mapped_column(
        String(50), nullable=False, default="pending",
        comment="pending | accepted | rejected",
    )
    expires_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
    )

    tenant: Mapped["Tenant"] = relationship("Tenant", lazy="noload")  # type: ignore[name-defined]

    def __repr__(self) -> str:
        return f"<Invitation id={self.id} email={self.email!r} status={self.status!r}>"
